### PR TITLE
Add fork endpoint

### PR DESCRIPTION
**Pull request by jamieliu386**

### CODE REVIEW

**Comment by connorbo97** [comment]
I want to wait to merge this until we have a frontend ready

**Comment by malsf21** [comment]
Fixed some merge conflicts. Might want to update namespacing to make things more consistent.

**Comment by malsf21** [comment]
Second thought - wondering if we can modularise this by calling createProgram. Feel like this should be doable somehow.

**Comment by malsf21** [comment]
@jamieliu386 this branch has lots of duplicated code w/ createProgram - do you think it'd make sense to bundle together the functionality of actually creating the program in one function? Not sure if that makes future work a bit tougher.

**Comment by jamieliu386** [comment]
Yeah, I think it makes sense to bundle the program creation functionality together. I don't currently foresee any issues with doing so!

**Comment by malsf21** [comment]
Quick bump on this, @krashanoff I think this is still mergeable but not sure. @jamieliu386 any insights?

**Comment by jamieliu386** [comment]
not sure if we need it anymore, since createProgram should work fine!

**Comment by malsf21** [comment]
> not sure if we need it anymore, since createProgram should work fine!

Oh I see, you're calling the create endpoint in the frontend anyways! Big brain move 😄 

If that's the case, I think this PR is fine to be closed - up to y'all if we'll end up needing this!

**Comment by jamieliu386** [comment]
> If that's the case, I think this PR is fine to be closed - up to y'all if we'll end up needing this!
Sounds good to me!

**Comment by krashanoff** [comment]
I'll leave the branch up in the event that we do want to end up merging this. Ultimately the Go backend will replace this but I think we still want to figure out this usage issue.

**Pull request closed without merging**
